#!/usr/bin/env python3
"""Spawn a pedestrian scenario into an already running world.

    ros2 launch amr_sim people.launch.py scenario:=static_people

Kept separate from the robot bringup on purpose. The world is generated by
tools/import_aws_warehouse.py, so anything written into it is destroyed on the
next import; and spawning from a scenario file means two runs of the same
scenario place people identically, which is what makes their detections
comparable between runs.
"""

import yaml

from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, OpaqueFunction
from launch.substitutions import (LaunchConfiguration, PathJoinSubstitution,
                                  TextSubstitution)
from launch_ros.actions import Node
from launch_ros.substitutions import FindPackageShare


def spawn_people(context, *_, **__):
    share = FindPackageShare('amr_sim')
    scenario = LaunchConfiguration('scenario').perform(context)
    path = PathJoinSubstitution(
        [share, 'scenarios', f'{scenario}.yaml']).perform(context)
    spec = yaml.safe_load(open(path))
    model = PathJoinSubstitution([share, 'models', 'person']).perform(context)

    nodes = []
    # Ground truth bridge. The simulator's pose feed is the LABEL ORACLE for
    # evaluation: it never enters the control path, only the scoring. See the
    # note at the top of docs/validation.md.
    world = LaunchConfiguration('world').perform(context)
    nodes.append(Node(
        package='amr_sim', executable='ground_truth_publisher', output='screen',
        parameters=[{'use_sim_time': True, 'world': world}]))
    # The true floorplan, latched for display and for scoring the SLAM map.
    # Same namespace and same rule as the pose oracle: evaluation only.
    # THE TRUTH MAP BELONGS TO THE WORLD. Both this publisher and the
    # pedestrian driver default to the AWS building, and the driver plans its
    # walkers' routes against whatever map it is given, so on a different world
    # the people navigate a coordinate space that does not overlap the one they
    # are standing in. Observed on the test track: routes checked against
    # x[-7.5,7.5] y[-11.0,11.0] while the track is x[0,24] y[0,12].
    truth_map = PathJoinSubstitution(
        [share, 'maps',
         [LaunchConfiguration('truth_map'), TextSubstitution(text='.yaml')]]
    ).perform(context)
    nodes.append(Node(
        package='amr_sim', executable='truth_map_publisher', output='screen',
        parameters=[{'use_sim_time': True, 'map_file': truth_map}]))

    # Anyone who moves needs a cmd_vel bridge and a driver. The key used to be
    # `path`, from the fixed-lane era, and after the switch to `wander` this
    # test matched nobody: the bridge and the driver were never launched at all,
    # so the figures stood still with no error anywhere to say why. Match on
    # either, so a scenario file cannot silently produce a dead crowd.
    walkers = [q for q in spec.get('people', []) if q.get('wander') or q.get('path')]
    if walkers:
        # One bridge entry per walker, ROS to Gazebo, feeding the VelocityControl
        # plugin the person model carries.
        nodes.append(Node(
            package='ros_gz_bridge', executable='parameter_bridge', output='screen',
            name='pedestrian_cmd_bridge',
            arguments=[
                f'/model/{q["name"]}/cmd_vel@geometry_msgs/msg/Twist]gz.msgs.Twist'
                for q in walkers],
            parameters=[{'use_sim_time': True}]))
        nodes.append(Node(
            package='amr_sim', executable='pedestrian_driver', output='screen',
            parameters=[{'use_sim_time': True, 'scenario_path': path,
                         'map_file': truth_map}]))

    for person in spec.get('people', []):
        nodes.append(Node(
            package='ros_gz_sim', executable='create', output='screen',
            name=f'spawn_{person["name"]}',
            arguments=[
                '-file', model,
                '-name', person['name'],
                '-x', str(person['x']),
                '-y', str(person['y']),
                '-z', '0.02',
                '-Y', str(person.get('yaw', 0.0)),
            ],
            parameters=[{'use_sim_time': True}]))
    return nodes


def generate_launch_description():
    return LaunchDescription([
        DeclareLaunchArgument(
            'scenario', default_value='static_people',
            description='name of a file under amr_sim/scenarios'),
        DeclareLaunchArgument(
            'world', default_value='warehouse',
            description='world name, used to find the ground truth pose feed'),
        DeclareLaunchArgument(
            'truth_map', default_value='warehouse_truth',
            description='ground truth map for this world, under amr_sim/maps'),
        OpaqueFunction(function=spawn_people),
    ])
